/* Champions League club field for simulations. name, flag (club nation), rating (~74-90, gameplay approximations). */
window.CL_CLUBS = [
  { name: "Real Madrid", flag: "🇪🇸", rating: 90 },
  { name: "Manchester City", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", rating: 90 },
  { name: "Bayern Munich", flag: "🇩🇪", rating: 89 },
  { name: "Liverpool", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", rating: 88 },
  { name: "Barcelona", flag: "🇪🇸", rating: 88 },
  { name: "Paris Saint-Germain", flag: "🇫🇷", rating: 87 },
  { name: "Inter Milan", flag: "🇮🇹", rating: 86 },
  { name: "Arsenal", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", rating: 86 },
  { name: "Atlético Madrid", flag: "🇪🇸", rating: 85 },
  { name: "Borussia Dortmund", flag: "🇩🇪", rating: 84 },
  { name: "Bayer Leverkusen", flag: "🇩🇪", rating: 84 },
  { name: "Juventus", flag: "🇮🇹", rating: 84 },
  { name: "AC Milan", flag: "🇮🇹", rating: 84 },
  { name: "Chelsea", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", rating: 84 },
  { name: "RB Leipzig", flag: "🇩🇪", rating: 83 },
  { name: "Atalanta", flag: "🇮🇹", rating: 83 },
  { name: "Napoli", flag: "🇮🇹", rating: 83 },
  { name: "Tottenham Hotspur", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", rating: 83 },
  { name: "Aston Villa", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", rating: 82 },
  { name: "Benfica", flag: "🇵🇹", rating: 82 },
  { name: "Porto", flag: "🇵🇹", rating: 82 },
  { name: "Sporting CP", flag: "🇵🇹", rating: 82 },
  { name: "Bologna", flag: "🇮🇹", rating: 80 },
  { name: "PSV Eindhoven", flag: "🇳🇱", rating: 81 },
  { name: "Ajax", flag: "🇳🇱", rating: 81 },
  { name: "Feyenoord", flag: "🇳🇱", rating: 80 },
  { name: "Marseille", flag: "🇫🇷", rating: 81 },
  { name: "AS Monaco", flag: "🇫🇷", rating: 81 },
  { name: "Galatasaray", flag: "🇹🇷", rating: 80 },
  { name: "Shakhtar Donetsk", flag: "🇺🇦", rating: 79 },
  { name: "Celtic", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", rating: 78 },
  { name: "Club Brugge", flag: "🇧🇪", rating: 78 },
  { name: "Red Star Belgrade", flag: "🇷🇸", rating: 77 },
  { name: "Young Boys", flag: "🇨🇭", rating: 76 },
  { name: "Sturm Graz", flag: "🇦🇹", rating: 75 },
  { name: "Slovan Bratislava", flag: "🇸🇰", rating: 74 }
];
