/* The 48-team field (2026-style expanded World Cup).
 * Each: name, flag, and an overall strength rating (~50-90) used by the match engine.
 * Ratings are subjective approximations for gameplay balance, not official rankings.
 */
window.NATIONS = [
  { name: "Argentina",    flag: "🇦🇷", rating: 89 },
  { name: "France",       flag: "🇫🇷", rating: 89 },
  { name: "Brazil",       flag: "🇧🇷", rating: 88 },
  { name: "England",      flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", rating: 87 },
  { name: "Spain",        flag: "🇪🇸", rating: 87 },
  { name: "Portugal",     flag: "🇵🇹", rating: 86 },
  { name: "Netherlands",  flag: "🇳🇱", rating: 85 },
  { name: "Germany",      flag: "🇩🇪", rating: 84 },
  { name: "Belgium",      flag: "🇧🇪", rating: 82 },
  { name: "Italy",        flag: "🇮🇹", rating: 82 },
  { name: "Croatia",      flag: "🇭🇷", rating: 81 },
  { name: "Uruguay",      flag: "🇺🇾", rating: 80 },
  { name: "Colombia",     flag: "🇨🇴", rating: 79 },
  { name: "Morocco",      flag: "🇲🇦", rating: 78 },
  { name: "Mexico",       flag: "🇲🇽", rating: 77 },
  { name: "USA",          flag: "🇺🇸", rating: 76 },
  { name: "Switzerland",  flag: "🇨🇭", rating: 76 },
  { name: "Denmark",      flag: "🇩🇰", rating: 76 },
  { name: "Senegal",      flag: "🇸🇳", rating: 75 },
  { name: "Japan",        flag: "🇯🇵", rating: 75 },
  { name: "Serbia",       flag: "🇷🇸", rating: 74 },
  { name: "Ecuador",      flag: "🇪🇨", rating: 73 },
  { name: "South Korea",  flag: "🇰🇷", rating: 73 },
  { name: "Poland",       flag: "🇵🇱", rating: 72 },
  { name: "Austria",      flag: "🇦🇹", rating: 72 },
  { name: "Turkey",       flag: "🇹🇷", rating: 72 },
  { name: "Ukraine",      flag: "🇺🇦", rating: 71 },
  { name: "Sweden",       flag: "🇸🇪", rating: 71 },
  { name: "Nigeria",      flag: "🇳🇬", rating: 71 },
  { name: "Ivory Coast",  flag: "🇨🇮", rating: 70 },
  { name: "Wales",        flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿", rating: 70 },
  { name: "Peru",         flag: "🇵🇪", rating: 69 },
  { name: "Chile",        flag: "🇨🇱", rating: 69 },
  { name: "Egypt",        flag: "🇪🇬", rating: 69 },
  { name: "Cameroon",     flag: "🇨🇲", rating: 68 },
  { name: "Ghana",        flag: "🇬🇭", rating: 68 },
  { name: "Australia",    flag: "🇦🇺", rating: 68 },
  { name: "Iran",         flag: "🇮🇷", rating: 68 },
  { name: "Tunisia",      flag: "🇹🇳", rating: 66 },
  { name: "Algeria",      flag: "🇩🇿", rating: 66 },
  { name: "Paraguay",     flag: "🇵🇾", rating: 65 },
  { name: "Scotland",     flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", rating: 65 },
  { name: "Greece",       flag: "🇬🇷", rating: 65 },
  { name: "Canada",       flag: "🇨🇦", rating: 64 },
  { name: "Costa Rica",   flag: "🇨🇷", rating: 62 },
  { name: "Saudi Arabia", flag: "🇸🇦", rating: 61 },
  { name: "Panama",       flag: "🇵🇦", rating: 59 },
  { name: "Qatar",        flag: "🇶🇦", rating: 57 }
];
